import type { RunState, CombatState } from '@codekeep/shared';
import type { GameSettings } from '../components/SettingsView.js';
import { execSync, execFileSync } from 'node:child_process';
import os from 'node:os';
import { writeFileSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const REPO = 'tooyipjee/codekeep';
const REPO_URL = `https://github.com/${REPO}`;

export interface BugReportContext {
  version: string;
  screen: string;
  run: RunState | null;
  combat: CombatState | null;
  settings: GameSettings;
  termCols: number;
  termRows: number;
}

export interface SubmitResult {
  success: boolean;
  issueUrl?: string;
  fallbackUrl?: string;
  error?: string;
}

function collectEnvironment(): string {
  const lines: string[] = [];
  lines.push(`- **OS**: ${os.platform()} ${os.release()} (${os.arch()})`);
  lines.push(`- **Node**: ${process.version}`);
  const shell = process.env.SHELL;
  lines.push(`- **Shell**: ${shell ? shell.split('/').pop() : 'unknown'}`);
  lines.push(`- **Terminal**: ${process.env.TERM_PROGRAM ?? process.env.TERM ?? 'unknown'}`);
  return lines.join('\n');
}

function collectRunState(run: RunState | null): string {
  if (!run) return '_No active run_';
  const lines: string[] = [];
  lines.push(`- **Act**: ${run.act}`);
  lines.push(`- **Floor**: ${run.currentNodeId ?? 'map'}`);
  lines.push(`- **Gate HP**: ${run.gateHp}/${run.gateMaxHp}`);
  lines.push(`- **Deck size**: ${run.deck.length}`);
  lines.push(`- **Fragments**: ${run.fragments}`);
  lines.push(`- **Seed**: \`${run.seed}\``);
  if (run.relics && run.relics.length > 0) {
    lines.push(`- **Relics**: ${run.relics.join(', ')}`);
  }
  if (run.gitBonuses && run.gitBonuses.length > 0) {
    lines.push(`- **Git bonuses**: ${run.gitBonuses.map(b => `${b.type}(+${b.value})`).join(', ')}`);
  }
  return lines.join('\n');
}

function collectCombatState(combat: CombatState | null): string {
  if (!combat) return '_Not in combat_';
  const lines: string[] = [];
  lines.push(`- **Turn**: ${combat.turn}`);
  lines.push(`- **Phase**: ${combat.phase}`);
  lines.push(`- **Resolve**: ${combat.resolve}/${combat.maxResolve}`);
  lines.push(`- **Gate HP**: ${combat.gateHp}/${combat.gateMaxHp} (Block: ${combat.gateBlock})`);
  lines.push(`- **Hand**: ${combat.hand.map(c => c.defId).join(', ')}`);
  lines.push(`- **Draw pile**: ${combat.drawPile.length} cards`);
  lines.push(`- **Discard pile**: ${combat.discardPile.length} cards`);

  const enemies: string[] = [];
  for (let col = 0; col < combat.columns.length; col++) {
    for (const e of combat.columns[col].enemies) {
      enemies.push(`Col${col + 1}:${e.templateId}(${e.hp}/${e.maxHp},row${e.row})`);
    }
    if (combat.columns[col].emplacement) {
      const emp = combat.columns[col].emplacement!;
      enemies.push(`Col${col + 1}:emp-${emp.cardDefId}(${emp.hp}/${emp.maxHp})`);
    }
  }
  lines.push(`- **Battlefield**: ${enemies.join(', ') || 'empty'}`);
  lines.push(`- **Seed**: \`${combat.seed}\``);
  return lines.join('\n');
}

function collectSettings(settings: GameSettings): string {
  const entries = Object.entries(settings)
    .map(([k, v]) => `${k}=${JSON.stringify(v)}`)
    .join(', ');
  return `\`${entries}\``;
}

function buildTitle(description: string): string {
  if (description.length > 60) return `Bug: ${description.slice(0, 57)}...`;
  return `Bug: ${description || 'Untitled bug report'}`;
}

export function buildBugReportBody(ctx: BugReportContext, description: string): string {
  return `## Bug Description

${description || '_No description provided_'}

## Environment

${collectEnvironment()}
- **CodeKeep version**: ${ctx.version}
- **Terminal size**: ${ctx.termCols}×${ctx.termRows}
- **Screen**: ${ctx.screen}
- **Settings**: ${collectSettings(ctx.settings)}

## Run State

${collectRunState(ctx.run)}

## Combat State

${collectCombatState(ctx.combat)}

---
_Auto-generated by CodeKeep bug reporter_`;
}

export function buildBugReportUrl(ctx: BugReportContext, description: string): string {
  let body = buildBugReportBody(ctx, description);
  if (body.length > 4000) {
    body = body.slice(0, 4000) + '\n\n_(truncated — install `gh` CLI for full reports)_';
  }
  const params = new URLSearchParams({
    title: buildTitle(description),
    body,
    labels: 'bug',
  });
  return `${REPO_URL}/issues/new?${params.toString()}`;
}

function hasGhCli(): boolean {
  try {
    execSync('gh --version', { stdio: 'ignore', timeout: 3000 });
    return true;
  } catch {
    return false;
  }
}

function submitViaGh(title: string, body: string): SubmitResult {
  const tmpFile = join(tmpdir(), `codekeep-bug-${Date.now()}.md`);
  try {
    writeFileSync(tmpFile, body, 'utf-8');
    const result = execFileSync('gh', [
      'issue', 'create',
      '--repo', REPO,
      '--title', title,
      '--body-file', tmpFile,
      '--label', 'bug',
    ], { encoding: 'utf-8', timeout: 15000, stdio: ['pipe', 'pipe', 'pipe'] });
    const url = result.trim().split('\n').pop()?.trim();
    return { success: true, issueUrl: url };
  } catch (err: any) {
    const msg = err.stderr?.toString() || err.message || 'Unknown error';
    if (msg.includes('auth') || msg.includes('login')) {
      return { success: false, error: 'gh not authenticated — run `gh auth login` first' };
    }
    return { success: false, error: msg.slice(0, 200) };
  } finally {
    try { unlinkSync(tmpFile); } catch {}
  }
}

export function submitBugReport(ctx: BugReportContext, description: string): SubmitResult {
  const title = buildTitle(description);
  const body = buildBugReportBody(ctx, description);

  if (hasGhCli()) {
    const result = submitViaGh(title, body);
    if (result.success) return result;
    return { ...result, fallbackUrl: buildBugReportUrl(ctx, description) };
  }

  return {
    success: false,
    fallbackUrl: buildBugReportUrl(ctx, description),
    error: 'GitHub CLI (gh) not found — install it from https://cli.github.com',
  };
}

export function openUrl(url: string): boolean {
  try {
    const platform = os.platform();
    if (platform === 'darwin') {
      execSync(`open "${url}"`, { stdio: 'ignore', timeout: 3000 });
    } else if (platform === 'win32') {
      execSync(`start "" "${url}"`, { stdio: 'ignore', timeout: 3000 });
    } else {
      execSync(`xdg-open "${url}"`, { stdio: 'ignore', timeout: 3000 });
    }
    return true;
  } catch {
    return false;
  }
}
